const store = [
  {beerName: 'Green Bomber',
  beerType: 'Imperial IPA',
  ingredients: 'adsfasdfasdfalskdjf;lsdjfkljalhsdkjfhaksjdhfkjasdhlajkhsdkljfhakjsdhfkjlahsdfkjahsldkjfhasdkjfhadskljfhllkajsdhfkjashfdkjhasdkjfhaksdjhfkjasdhalkjsdhfkjhasdlkjfhasdlkjfhakjsdhlkjajskdhfkljahsdkfjhasdkjhfkajdshfkjhadskjlfhkajsdhfkjahsdkjfhakjsdhfkjasdhfkjhasdkjfhaskjdhfkajsdhfkjhaskjdfhaskjdhfkjashfdkjhaskljdhakjsdhflkjadshlkfjhdklajfhaklsdjhfkjlashdklfjhasdkjfhakjsdhfkjasdhfkhaskjdhfkajshdfkjlasdh',
  water: '',
  postBrewIngredients: '',
  totalCosts: '$80.00',
  brewDate: '2013-04-28T18:12:38.197Z',
  timeStarted: '',
  weather: '70',
  mashNotes: '',
  boilNotes: '',
  postBoilNotes: '',
  ogReading: '1.085',
  dateStartFermentation: '2013-05-07T18:12:38.197Z',
  fermentationNotes: '',
  packagingDate: '',
  hydrometerReading: '1.015',
  typeOfPackaging: '',
  notesAboutPackaging: '',
  uuid: 'f7ff7086-c474-44a0-bcca-f2fde6fd3118',
  },
  {beerName: 'Red Dawn',
  beerType: 'American Amber Ale',
  ingredients: '',
  water: '',
  postBrewIngredients: '',
  totalCosts: '',
  brewDate: '2013-03-26T18:12:38.197Z',
  timeStarted: '',
  weather: '',
  mashNotes: '',
  boilNotes: '',
  postBoilNotes: '',
  ogReading: '',
  dateStartFermentation: '',
  fermentationNotes: '',
  packagingDate: '',
  hydrometerReading: '',
  typeOfPackaging: '',
  notesAboutPackaging: '',
  uuid: '8c4516d0-bc37-4251-beca-43c8332eee47',
}
];

module.exports = store;
