const store = [
  {beerName: 'Green Bomber',
  beerType: 'Imperial IPA',
  ingredients: '',
  water: '',
  postBrewIngredients: '',
  totalCosts: '$80.00',
  brewDate: 'April 28th 2013',
  timeStarted: '',
  weather: '70',
  mashNotes: '',
  boilNotes: '',
  postBoilNotes: '',
  ogReading: '1.085',
  dateStartFermentation: 'April 28th 2013',
  fermentationNotes: '',
  packagingDate: '',
  hydrometerReading: '1.015',
  typeOfPackaging: '',
  notesAboutPackaging: '',
  },
  {beerName: 'Red Dawn',
  beerType: 'American Amber Ale',
  ingredients: '',
  water: '',
  postBrewIngredients: '',
  totalCosts: '',
  brewDate: 'March 26th 2013',
  timeStarted: '',
  weather: '',
  mashNotes: '',
  boilNotes: '',
  postBoilNotes: '',
  ogReading: '',
  dateStartFermentation: '',
  fermentationNotes: '',
  packagingDate: '',
  hydrometerReading: '',
  typeOfPackaging: '',
  notesAboutPackaging: '',
}
];

module.exports = store;
